export enum DemolisherName {
  DEMOLISHER_DEVOURER = "Demolisher Devourer",
  DEMOLISHER_EXPIRED = "Demolisher Expired",
  DEMOLISHER_BAILIFF = "Demolisher Bailiff",
  DEMOLISHER_HEAVY_GUNNER = "Demolisher Heavy Gunner",
  DEMOLISHER_NOX = "Demolisher Nox",
  DEMOLISHER_KUVA_GUARDIAN = "Demolisher Kuva Guardian",
  DEMOLISHER_ANTI_MOA = "Demolisher Anti MOA",
  DEMOLISHER_BURSA = "Demolisher Bursa",
  DEMOLISHER_HYENA = "Demolisher Hyena",
  DEMOLISHER_MACHINIST = "Demolisher Machinist",
  DEMOLYST_HEQET = "Demolyst Heqet",
  DEMOLYST_MACHINIST = "Demolyst Machinist",
  DEMOLYST_MOA = "Demolyst MOA",
  DEMOLYST_SATYR = "Demolyst Satyr",
  DEMOLISHER_BOILER = "Demolisher Boiler",
  DEMOLISHER_CHARGER = "Demolisher Charger",
  DEMOLISHER_JUGGERNAUT = "Demolisher Juggernaut",
  DEMOLISHER_THRASHER = "Demolisher Thrasher",
}
